### ISSUE TITLE
QLoRa support

### ISSUE THREAD

**Issue by bitnom** [hyperonym/basaran#202]
does it qlora?

**Comment by peakji** [comment]
No yet. But QLoRA, GPTQ, and 4-bit quantization are on the todo list.

**Comment by LoopControl** [comment]
GPTQ would be fantastic. The 4 bit implementation in bitsandbytes has very slow inference speeds (like 8X slower).

For GPTQ integration, [AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ) is ideal since it provides a higher level abstraction than the low-level and always changing gptq-for-llama repo.

**Comment by 0xDigest** [comment]
> No yet. But QLoRA, GPTQ, and 4-bit quantization are on the todo list.

It'd be interesting if this could support multiple LoRa adapters[0] that could be swapped using the unused model parameter.

[0] https://github.com/huggingface/peft/blob/main/examples/multi_adapter_examples/PEFT_Multi_LoRA_Inference.ipynb

**Comment by peakji** [comment]
4-bit quantization with QLoRA is added in https://github.com/hyperonym/basaran/pull/209.

Feel free to open another issue for GPTQ integration.
