### ISSUE TITLE
API Usage - iOS Shortcuts

### ISSUE THREAD

**Issue by gabeanelson** [hyperonym/basaran#61]
I want to integrate basaran into iOS Shortcuts, but I'm unsure how to use the API. With the existing iOS Shortcuts, for ChatGP, you only need an API key. 

Is there a good place to look for documentation on API usage, or does anyone have an iOS Shortcut that leverages basaran, willing to share it with us?

**Comment by peakji** [comment]
After running Basaran, its API format is consistent with the OpenAI text completion API, and you can refer to their [documentation](https://platform.openai.com/docs/api-reference/completions/create) directly. Since Basaran is self-hosted, there is no need to use an API Key. However, some client libraries for OpenAI require the API Key field to be non-empty, so you can just type in some random characters.

**Comment by gabeanelson** [comment]
I just tested it and you are correct. This is great!
