### ISSUE TITLE
Chat broken

### ISSUE THREAD

**Issue by hassansf** [hyperonym/basaran#62]
I asked chat gpt to write a code, instead it writes garbage, completely irrelevant content. Any explanation?
I am using docker container in Synology

**Comment by peakji** [comment]
Hi @hassansf , which model are you using with Basaran? Since you mentioned that you are running on Synology, I assume that you might be using a small model (like the default [bloomz-560m](https://huggingface.co/bigscience/bloomz-560m)).

Different models have different ranges of capabilities, and coding tasks may require more powerful models. You can browse on the [Hugging Face Hub](https://huggingface.co/models?pipeline_tag=text-generation) to find some models that may be more suitable for your needs.

Additionally, some models that have been instruction-tuned or fine-tuned for dialogue may require special prompt formats that vary depending on the model. Generally, these formats and templates will be explained on the model's README page.

**Comment by hassansf** [comment]
hello @peakji, I am actually not using NAS hardware instead it is an old Optiplex with 8GB RAM. Also the CPU usage will reach at 99% so I had to remove the container. I used this command to install Basaran:

docker run -d --name=Basaran \
-p 5477:80 \
-e MODEL=gpt2 \
--restart always \
hyperonym/basaran:0.12.0

It installs without error and the response time is unusually fast but the content written by chatgpt is not related to the question at all. As if it is reading news.

**Comment by peakji** [comment]
>  Also the CPU usage will reach at 99% so I had to remove the container.

When the model is inferring, it is normal for the CPU utilization to reach 100%. It should return to 0% after the output is complete.

> It installs without error and the response time is unusually fast but the content written by chatgpt is not related to the question at all. As if it is reading news.

[GPT-2](https://en.wikipedia.org/wiki/GPT-2) (released in 2019) is not [ChatGPT](https://en.wikipedia.org/wiki/ChatGPT) (2022) and has not undergone instruction tuning, so it is only suitable for text completion tasks. If you want similar performance to ChatGPT, you can consider using [Bloomz](https://huggingface.co/bigscience/bloomz) or [ChatGLM](https://github.com/hyperonym/basaran/blob/master/deployments/bundle/chatglm-6b.Dockerfile).

**Comment by hassansf** [comment]
Much appreciated. Thank you.
